= Development Logs =

== March 2025 ==

=== 2025-03-10 ===

Better results for 2D functions! One of the problem was connected to data distribution. I created a 'line', not a 'plane' of features and, because of that, NN was approximating the function perfectly, but only on a narrow line of features, but a 2D-integral is a volume under a plane, not under the line (if boundaries does not define otherwise, certainly).

UPDATE: BIG success! I managed to reach 2 semi-correct (relative to standard numerical integration methods quad and trapz) digits for Oscillatory 2D function and 3 semi-correct digits for Corner Peak 2D. Both functions are from Genz numerical integration testing package.

== February 2025 ==

=== 2025-02-28 ===

Maybe a https://arxiv.org/pdf/2404.19756[KAN] neural network will be more useful for the function approximation. Hope KAN be integrated!!!

=== 2025-02-27 ===

Devlogs are now here, the https://github.com/GrindelfP/project-skuld/blob/main/README.adoc[README] should contain clean information on the project.

=== Earlier in February 2025 ===

- Tried using the task for the 1d integration - good accuracy achieved.
- Tried using the task for the 2d integration - not so good.
  
== Before February 2025 ==

- Creatred implementation for 1d integrals using PyTorch library for the neural network model.
- Created a jupyter-notebook https://github.com/GrindelfP/nni-tutorial/tree/main[tutorial] on neural network integration of a 1d functions.
