= Project "Skuld" =

Preamble: Skuld is a Norn (a fate goddess) from Scandinavian mythology. My choice when picking her name as a title for my project as well as (probably) my numerical integration library is dictated by the nature of the goddess: she fortells what should happen the same as a neural network fortell the function for inputed parameters, not calculates it. Also the reason is that I like the Scandinavian mythology pretty much.

== Description ==
My Bachelor's degree diploma thesis. The main goal is to implement a numerical integration library for neural network-based numerical integration of a complex dimensional functions. 

== Project structure ==

* *diploma-text* directory contains text assets for my diploma tesis.
* *cat* directory contains the sourse code of the project:
  ** *nn-c-test* directory contains C programming language attempt on creating the NNI system (was a bad idea and will not be developed later).
  ** *nn-python* directory contains main implementations using the Python programming language (moslty Jupyter notebooks, but some source .py code also).
    *** *lib* directory contains .py files and will be the main storage space for my library.
    *** *main-notebooks* directory contains the "good" Jupyter notebooks (those, I recon, containing the best code and results).
    *** *playground* other Jupyter notebooks as well as unfinished, abandoned, banished and wrong-idea code.

== Goals ==

Main goal:
*Implement the Skuld library which can be used to integrate multi-dimensional functions.*

Less general goals can be observed under the https://github.com/GrindelfP/project-skuld/milestones[Milestones] section. 
