= Project "Skuld" =

Preamble: Skuld is a Norn (a fate goddess) from Scandinavian mythology. My choice when picking her name as a title for my project as well as (probably) my numerical integration library is dictated by the nature of the goddess: she fortells what should happen the same as a neural network fortell the function for inputed parameters, not calculates it. Also the reason is that I like the Scandinavian mythology pretty much.

== Description ==
My Bachelor's degree diploma thesis. The main goal is to implement a numerical integration library for neural network-based numerical integration of a complex dimensional functions. 

== Project structure ==

== Goals ==

Main goal:
*Implement the Skuld library which can be used to integrate multi-dimensional functions.*

Less general goals can be observed under the https://github.com/GrindelfP/project-skuld/milestones[Milestones] section. 

== Development ==

*_Before Feb 2025_*

- Creatred implementation for 1d integrals using PyTorch library for the neural network model.
- Created a jupyter-notebook https://github.com/GrindelfP/nni-tutorial/tree/main[tutorial] on neural network integration of a 1d functions.

*_Feb 2025_*

- Tried using the task for the 1d integration - good accuracy achieved.
- Tried using the task for the 2d integration - not so good.
